// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc;

public final class FlightServiceImpl {
  private FlightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_LocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_LocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_LocationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_LocationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_DateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_DateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_DateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_DateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014flight.proto\022\030com.alexeyre.grpc.flight" +
      "\"&\n\017LocationRequest\022\023\n\013destination\030\001 \001(\t" +
      "\"\'\n\020LocationResponse\022\023\n\013destination\030\001 \001(" +
      "\t\"\033\n\013DateRequest\022\014\n\004date\030\001 \001(\t\"\034\n\014DateRe" +
      "sponse\022\014\n\004date\030\001 \001(\t2\333\001\n\rFlightService\022i" +
      "\n\016flightLocation\022).com.alexeyre.grpc.fli" +
      "ght.LocationRequest\032*.com.alexeyre.grpc." +
      "flight.LocationResponse\"\000\022_\n\nflightDate\022" +
      "%.com.alexeyre.grpc.flight.DateRequest\032&" +
      ".com.alexeyre.grpc.flight.DateResponse\"\000" +
      "(\001B(\n\021com.alexeyre.grpcB\021FlightServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alexeyre_grpc_flight_LocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alexeyre_grpc_flight_LocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_LocationRequest_descriptor,
        new java.lang.String[] { "Destination", });
    internal_static_com_alexeyre_grpc_flight_LocationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alexeyre_grpc_flight_LocationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_LocationResponse_descriptor,
        new java.lang.String[] { "Destination", });
    internal_static_com_alexeyre_grpc_flight_DateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alexeyre_grpc_flight_DateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_DateRequest_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_com_alexeyre_grpc_flight_DateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_alexeyre_grpc_flight_DateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_DateResponse_descriptor,
        new java.lang.String[] { "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
