// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc;

/**
 * Protobuf type {@code com.alexeyre.grpc.flight.ListRequest}
 */
public  final class ListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.flight.ListRequest)
    ListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListRequest.newBuilder() to construct.
  private ListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListRequest() {
    location1_ = "";
    location2_ = "";
    location3_ = "";
    location4_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            location1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            location2_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            location3_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            location4_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.ListRequest.class, com.alexeyre.grpc.ListRequest.Builder.class);
  }

  public static final int LOCATION1_FIELD_NUMBER = 1;
  private volatile java.lang.Object location1_;
  /**
   * <code>string location1 = 1;</code>
   */
  public java.lang.String getLocation1() {
    java.lang.Object ref = location1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location1_ = s;
      return s;
    }
  }
  /**
   * <code>string location1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLocation1Bytes() {
    java.lang.Object ref = location1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION2_FIELD_NUMBER = 2;
  private volatile java.lang.Object location2_;
  /**
   * <code>string location2 = 2;</code>
   */
  public java.lang.String getLocation2() {
    java.lang.Object ref = location2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location2_ = s;
      return s;
    }
  }
  /**
   * <code>string location2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLocation2Bytes() {
    java.lang.Object ref = location2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION3_FIELD_NUMBER = 3;
  private volatile java.lang.Object location3_;
  /**
   * <code>string location3 = 3;</code>
   */
  public java.lang.String getLocation3() {
    java.lang.Object ref = location3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location3_ = s;
      return s;
    }
  }
  /**
   * <code>string location3 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLocation3Bytes() {
    java.lang.Object ref = location3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION4_FIELD_NUMBER = 4;
  private volatile java.lang.Object location4_;
  /**
   * <code>string location4 = 4;</code>
   */
  public java.lang.String getLocation4() {
    java.lang.Object ref = location4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location4_ = s;
      return s;
    }
  }
  /**
   * <code>string location4 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLocation4Bytes() {
    java.lang.Object ref = location4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLocation1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, location1_);
    }
    if (!getLocation2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, location2_);
    }
    if (!getLocation3Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, location3_);
    }
    if (!getLocation4Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, location4_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLocation1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, location1_);
    }
    if (!getLocation2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, location2_);
    }
    if (!getLocation3Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, location3_);
    }
    if (!getLocation4Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, location4_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.ListRequest)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.ListRequest other = (com.alexeyre.grpc.ListRequest) obj;

    boolean result = true;
    result = result && getLocation1()
        .equals(other.getLocation1());
    result = result && getLocation2()
        .equals(other.getLocation2());
    result = result && getLocation3()
        .equals(other.getLocation3());
    result = result && getLocation4()
        .equals(other.getLocation4());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCATION1_FIELD_NUMBER;
    hash = (53 * hash) + getLocation1().hashCode();
    hash = (37 * hash) + LOCATION2_FIELD_NUMBER;
    hash = (53 * hash) + getLocation2().hashCode();
    hash = (37 * hash) + LOCATION3_FIELD_NUMBER;
    hash = (53 * hash) + getLocation3().hashCode();
    hash = (37 * hash) + LOCATION4_FIELD_NUMBER;
    hash = (53 * hash) + getLocation4().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.ListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.ListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.ListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.ListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.ListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.flight.ListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.flight.ListRequest)
      com.alexeyre.grpc.ListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.ListRequest.class, com.alexeyre.grpc.ListRequest.Builder.class);
    }

    // Construct using com.alexeyre.grpc.ListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      location1_ = "";

      location2_ = "";

      location3_ = "";

      location4_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.ListRequest getDefaultInstanceForType() {
      return com.alexeyre.grpc.ListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.ListRequest build() {
      com.alexeyre.grpc.ListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.ListRequest buildPartial() {
      com.alexeyre.grpc.ListRequest result = new com.alexeyre.grpc.ListRequest(this);
      result.location1_ = location1_;
      result.location2_ = location2_;
      result.location3_ = location3_;
      result.location4_ = location4_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.ListRequest) {
        return mergeFrom((com.alexeyre.grpc.ListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.ListRequest other) {
      if (other == com.alexeyre.grpc.ListRequest.getDefaultInstance()) return this;
      if (!other.getLocation1().isEmpty()) {
        location1_ = other.location1_;
        onChanged();
      }
      if (!other.getLocation2().isEmpty()) {
        location2_ = other.location2_;
        onChanged();
      }
      if (!other.getLocation3().isEmpty()) {
        location3_ = other.location3_;
        onChanged();
      }
      if (!other.getLocation4().isEmpty()) {
        location4_ = other.location4_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.ListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.ListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object location1_ = "";
    /**
     * <code>string location1 = 1;</code>
     */
    public java.lang.String getLocation1() {
      java.lang.Object ref = location1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocation1Bytes() {
      java.lang.Object ref = location1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location1 = 1;</code>
     */
    public Builder setLocation1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location1 = 1;</code>
     */
    public Builder clearLocation1() {
      
      location1_ = getDefaultInstance().getLocation1();
      onChanged();
      return this;
    }
    /**
     * <code>string location1 = 1;</code>
     */
    public Builder setLocation1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object location2_ = "";
    /**
     * <code>string location2 = 2;</code>
     */
    public java.lang.String getLocation2() {
      java.lang.Object ref = location2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocation2Bytes() {
      java.lang.Object ref = location2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location2 = 2;</code>
     */
    public Builder setLocation2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location2 = 2;</code>
     */
    public Builder clearLocation2() {
      
      location2_ = getDefaultInstance().getLocation2();
      onChanged();
      return this;
    }
    /**
     * <code>string location2 = 2;</code>
     */
    public Builder setLocation2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object location3_ = "";
    /**
     * <code>string location3 = 3;</code>
     */
    public java.lang.String getLocation3() {
      java.lang.Object ref = location3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocation3Bytes() {
      java.lang.Object ref = location3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location3 = 3;</code>
     */
    public Builder setLocation3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location3 = 3;</code>
     */
    public Builder clearLocation3() {
      
      location3_ = getDefaultInstance().getLocation3();
      onChanged();
      return this;
    }
    /**
     * <code>string location3 = 3;</code>
     */
    public Builder setLocation3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location3_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object location4_ = "";
    /**
     * <code>string location4 = 4;</code>
     */
    public java.lang.String getLocation4() {
      java.lang.Object ref = location4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocation4Bytes() {
      java.lang.Object ref = location4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location4 = 4;</code>
     */
    public Builder setLocation4(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location4 = 4;</code>
     */
    public Builder clearLocation4() {
      
      location4_ = getDefaultInstance().getLocation4();
      onChanged();
      return this;
    }
    /**
     * <code>string location4 = 4;</code>
     */
    public Builder setLocation4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location4_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.flight.ListRequest)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.flight.ListRequest)
  private static final com.alexeyre.grpc.ListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.ListRequest();
  }

  public static com.alexeyre.grpc.ListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListRequest>() {
    @java.lang.Override
    public ListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.ListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

