// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc;

public interface LocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.LocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string destination = 1;</code>
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 1;</code>
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
