// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc;

public interface PeopleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.PeopleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 passengers = 1;</code>
   */
  int getPassengers();
}
