// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rental.proto

package com.alexeyre.grpc;

public interface RentalBookingDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.rental.RentalBookingDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
