// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rental.proto

package com.alexeyre.grpc;

public interface RentalDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.rental.RentalDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string carName = 1;</code>
   */
  java.lang.String getCarName();
  /**
   * <code>string carName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCarNameBytes();

  /**
   * <code>string carType = 2;</code>
   */
  java.lang.String getCarType();
  /**
   * <code>string carType = 2;</code>
   */
  com.google.protobuf.ByteString
      getCarTypeBytes();

  /**
   * <code>string carModel = 3;</code>
   */
  java.lang.String getCarModel();
  /**
   * <code>string carModel = 3;</code>
   */
  com.google.protobuf.ByteString
      getCarModelBytes();
}
