// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rental.proto

package com.alexeyre.grpc;

public interface RentalAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.rental.RentalAvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string empty = 1;</code>
   */
  java.lang.String getEmpty();
  /**
   * <code>string empty = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmptyBytes();
}
