// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rental.proto

package com.alexeyre.grpc;

public interface RentalListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.rental.RentalListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rentals = 1;</code>
   */
  java.lang.String getRentals();
  /**
   * <code>string rentals = 1;</code>
   */
  com.google.protobuf.ByteString
      getRentalsBytes();
}
