// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface BookingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.BookingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
