// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface BookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.BookingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ticketType = 1;</code>
   */
  java.lang.String getTicketType();
  /**
   * <code>string ticketType = 1;</code>
   */
  com.google.protobuf.ByteString
      getTicketTypeBytes();

  /**
   * <code>string seatPref = 2;</code>
   */
  java.lang.String getSeatPref();
  /**
   * <code>string seatPref = 2;</code>
   */
  com.google.protobuf.ByteString
      getSeatPrefBytes();

  /**
   * <code>string firstname = 3;</code>
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string surname = 4;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 4;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();
}
