// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

/**
 * Protobuf type {@code com.alexeyre.grpc.flight.DetailsResponse}
 */
public  final class DetailsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.flight.DetailsResponse)
    DetailsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DetailsResponse.newBuilder() to construct.
  private DetailsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DetailsResponse() {
    destination_ = "";
    departureDate_ = "";
    departureTime_ = "";
    flightDuration_ = "";
    arrivalTime_ = "";
    flightNumber_ = "";
    returnLocation_ = "";
    returnDate_ = "";
    returnTime_ = "";
    flightReturnDuration_ = "";
    returnArrivalTime_ = "";
    passengers_ = 0;
    price_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DetailsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            destination_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            departureDate_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            departureTime_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            flightDuration_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            arrivalTime_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            flightNumber_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            returnLocation_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            returnDate_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            returnTime_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            flightReturnDuration_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            returnArrivalTime_ = s;
            break;
          }
          case 96: {

            passengers_ = input.readInt32();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            price_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DetailsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DetailsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.flight.DetailsResponse.class, com.alexeyre.grpc.flight.DetailsResponse.Builder.class);
  }

  public static final int DESTINATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object destination_;
  /**
   * <code>string destination = 1;</code>
   */
  public java.lang.String getDestination() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destination_ = s;
      return s;
    }
  }
  /**
   * <code>string destination = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationBytes() {
    java.lang.Object ref = destination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTUREDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object departureDate_;
  /**
   * <code>string departureDate = 2;</code>
   */
  public java.lang.String getDepartureDate() {
    java.lang.Object ref = departureDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departureDate_ = s;
      return s;
    }
  }
  /**
   * <code>string departureDate = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDepartureDateBytes() {
    java.lang.Object ref = departureDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departureDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURETIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object departureTime_;
  /**
   * <code>string departureTime = 3;</code>
   */
  public java.lang.String getDepartureTime() {
    java.lang.Object ref = departureTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departureTime_ = s;
      return s;
    }
  }
  /**
   * <code>string departureTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDepartureTimeBytes() {
    java.lang.Object ref = departureTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departureTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLIGHTDURATION_FIELD_NUMBER = 4;
  private volatile java.lang.Object flightDuration_;
  /**
   * <code>string flightDuration = 4;</code>
   */
  public java.lang.String getFlightDuration() {
    java.lang.Object ref = flightDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flightDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string flightDuration = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFlightDurationBytes() {
    java.lang.Object ref = flightDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flightDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVALTIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object arrivalTime_;
  /**
   * <code>string arrivalTime = 5;</code>
   */
  public java.lang.String getArrivalTime() {
    java.lang.Object ref = arrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string arrivalTime = 5;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalTimeBytes() {
    java.lang.Object ref = arrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLIGHTNUMBER_FIELD_NUMBER = 6;
  private volatile java.lang.Object flightNumber_;
  /**
   * <code>string flightNumber = 6;</code>
   */
  public java.lang.String getFlightNumber() {
    java.lang.Object ref = flightNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flightNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string flightNumber = 6;</code>
   */
  public com.google.protobuf.ByteString
      getFlightNumberBytes() {
    java.lang.Object ref = flightNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flightNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNLOCATION_FIELD_NUMBER = 7;
  private volatile java.lang.Object returnLocation_;
  /**
   * <code>string returnLocation = 7;</code>
   */
  public java.lang.String getReturnLocation() {
    java.lang.Object ref = returnLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string returnLocation = 7;</code>
   */
  public com.google.protobuf.ByteString
      getReturnLocationBytes() {
    java.lang.Object ref = returnLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNDATE_FIELD_NUMBER = 8;
  private volatile java.lang.Object returnDate_;
  /**
   * <code>string returnDate = 8;</code>
   */
  public java.lang.String getReturnDate() {
    java.lang.Object ref = returnDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnDate_ = s;
      return s;
    }
  }
  /**
   * <code>string returnDate = 8;</code>
   */
  public com.google.protobuf.ByteString
      getReturnDateBytes() {
    java.lang.Object ref = returnDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNTIME_FIELD_NUMBER = 9;
  private volatile java.lang.Object returnTime_;
  /**
   * <code>string returnTime = 9;</code>
   */
  public java.lang.String getReturnTime() {
    java.lang.Object ref = returnTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnTime_ = s;
      return s;
    }
  }
  /**
   * <code>string returnTime = 9;</code>
   */
  public com.google.protobuf.ByteString
      getReturnTimeBytes() {
    java.lang.Object ref = returnTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLIGHTRETURNDURATION_FIELD_NUMBER = 10;
  private volatile java.lang.Object flightReturnDuration_;
  /**
   * <code>string flightReturnDuration = 10;</code>
   */
  public java.lang.String getFlightReturnDuration() {
    java.lang.Object ref = flightReturnDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      flightReturnDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string flightReturnDuration = 10;</code>
   */
  public com.google.protobuf.ByteString
      getFlightReturnDurationBytes() {
    java.lang.Object ref = flightReturnDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      flightReturnDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETURNARRIVALTIME_FIELD_NUMBER = 11;
  private volatile java.lang.Object returnArrivalTime_;
  /**
   * <code>string returnArrivalTime = 11;</code>
   */
  public java.lang.String getReturnArrivalTime() {
    java.lang.Object ref = returnArrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnArrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string returnArrivalTime = 11;</code>
   */
  public com.google.protobuf.ByteString
      getReturnArrivalTimeBytes() {
    java.lang.Object ref = returnArrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnArrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSENGERS_FIELD_NUMBER = 12;
  private int passengers_;
  /**
   * <code>int32 passengers = 12;</code>
   */
  public int getPassengers() {
    return passengers_;
  }

  public static final int PRICE_FIELD_NUMBER = 13;
  private volatile java.lang.Object price_;
  /**
   * <code>string price = 13;</code>
   */
  public java.lang.String getPrice() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>string price = 13;</code>
   */
  public com.google.protobuf.ByteString
      getPriceBytes() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDestinationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, destination_);
    }
    if (!getDepartureDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, departureDate_);
    }
    if (!getDepartureTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, departureTime_);
    }
    if (!getFlightDurationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, flightDuration_);
    }
    if (!getArrivalTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, arrivalTime_);
    }
    if (!getFlightNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, flightNumber_);
    }
    if (!getReturnLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, returnLocation_);
    }
    if (!getReturnDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, returnDate_);
    }
    if (!getReturnTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, returnTime_);
    }
    if (!getFlightReturnDurationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, flightReturnDuration_);
    }
    if (!getReturnArrivalTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, returnArrivalTime_);
    }
    if (passengers_ != 0) {
      output.writeInt32(12, passengers_);
    }
    if (!getPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, price_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDestinationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, destination_);
    }
    if (!getDepartureDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, departureDate_);
    }
    if (!getDepartureTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, departureTime_);
    }
    if (!getFlightDurationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, flightDuration_);
    }
    if (!getArrivalTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, arrivalTime_);
    }
    if (!getFlightNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, flightNumber_);
    }
    if (!getReturnLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, returnLocation_);
    }
    if (!getReturnDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, returnDate_);
    }
    if (!getReturnTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, returnTime_);
    }
    if (!getFlightReturnDurationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, flightReturnDuration_);
    }
    if (!getReturnArrivalTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, returnArrivalTime_);
    }
    if (passengers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, passengers_);
    }
    if (!getPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, price_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.flight.DetailsResponse)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.flight.DetailsResponse other = (com.alexeyre.grpc.flight.DetailsResponse) obj;

    boolean result = true;
    result = result && getDestination()
        .equals(other.getDestination());
    result = result && getDepartureDate()
        .equals(other.getDepartureDate());
    result = result && getDepartureTime()
        .equals(other.getDepartureTime());
    result = result && getFlightDuration()
        .equals(other.getFlightDuration());
    result = result && getArrivalTime()
        .equals(other.getArrivalTime());
    result = result && getFlightNumber()
        .equals(other.getFlightNumber());
    result = result && getReturnLocation()
        .equals(other.getReturnLocation());
    result = result && getReturnDate()
        .equals(other.getReturnDate());
    result = result && getReturnTime()
        .equals(other.getReturnTime());
    result = result && getFlightReturnDuration()
        .equals(other.getFlightReturnDuration());
    result = result && getReturnArrivalTime()
        .equals(other.getReturnArrivalTime());
    result = result && (getPassengers()
        == other.getPassengers());
    result = result && getPrice()
        .equals(other.getPrice());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDestination().hashCode();
    hash = (37 * hash) + DEPARTUREDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureDate().hashCode();
    hash = (37 * hash) + DEPARTURETIME_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureTime().hashCode();
    hash = (37 * hash) + FLIGHTDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getFlightDuration().hashCode();
    hash = (37 * hash) + ARRIVALTIME_FIELD_NUMBER;
    hash = (53 * hash) + getArrivalTime().hashCode();
    hash = (37 * hash) + FLIGHTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getFlightNumber().hashCode();
    hash = (37 * hash) + RETURNLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getReturnLocation().hashCode();
    hash = (37 * hash) + RETURNDATE_FIELD_NUMBER;
    hash = (53 * hash) + getReturnDate().hashCode();
    hash = (37 * hash) + RETURNTIME_FIELD_NUMBER;
    hash = (53 * hash) + getReturnTime().hashCode();
    hash = (37 * hash) + FLIGHTRETURNDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getFlightReturnDuration().hashCode();
    hash = (37 * hash) + RETURNARRIVALTIME_FIELD_NUMBER;
    hash = (53 * hash) + getReturnArrivalTime().hashCode();
    hash = (37 * hash) + PASSENGERS_FIELD_NUMBER;
    hash = (53 * hash) + getPassengers();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.flight.DetailsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.flight.DetailsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.flight.DetailsResponse)
      com.alexeyre.grpc.flight.DetailsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DetailsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DetailsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.flight.DetailsResponse.class, com.alexeyre.grpc.flight.DetailsResponse.Builder.class);
    }

    // Construct using com.alexeyre.grpc.flight.DetailsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      destination_ = "";

      departureDate_ = "";

      departureTime_ = "";

      flightDuration_ = "";

      arrivalTime_ = "";

      flightNumber_ = "";

      returnLocation_ = "";

      returnDate_ = "";

      returnTime_ = "";

      flightReturnDuration_ = "";

      returnArrivalTime_ = "";

      passengers_ = 0;

      price_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DetailsResponse_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DetailsResponse getDefaultInstanceForType() {
      return com.alexeyre.grpc.flight.DetailsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DetailsResponse build() {
      com.alexeyre.grpc.flight.DetailsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DetailsResponse buildPartial() {
      com.alexeyre.grpc.flight.DetailsResponse result = new com.alexeyre.grpc.flight.DetailsResponse(this);
      result.destination_ = destination_;
      result.departureDate_ = departureDate_;
      result.departureTime_ = departureTime_;
      result.flightDuration_ = flightDuration_;
      result.arrivalTime_ = arrivalTime_;
      result.flightNumber_ = flightNumber_;
      result.returnLocation_ = returnLocation_;
      result.returnDate_ = returnDate_;
      result.returnTime_ = returnTime_;
      result.flightReturnDuration_ = flightReturnDuration_;
      result.returnArrivalTime_ = returnArrivalTime_;
      result.passengers_ = passengers_;
      result.price_ = price_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.flight.DetailsResponse) {
        return mergeFrom((com.alexeyre.grpc.flight.DetailsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.flight.DetailsResponse other) {
      if (other == com.alexeyre.grpc.flight.DetailsResponse.getDefaultInstance()) return this;
      if (!other.getDestination().isEmpty()) {
        destination_ = other.destination_;
        onChanged();
      }
      if (!other.getDepartureDate().isEmpty()) {
        departureDate_ = other.departureDate_;
        onChanged();
      }
      if (!other.getDepartureTime().isEmpty()) {
        departureTime_ = other.departureTime_;
        onChanged();
      }
      if (!other.getFlightDuration().isEmpty()) {
        flightDuration_ = other.flightDuration_;
        onChanged();
      }
      if (!other.getArrivalTime().isEmpty()) {
        arrivalTime_ = other.arrivalTime_;
        onChanged();
      }
      if (!other.getFlightNumber().isEmpty()) {
        flightNumber_ = other.flightNumber_;
        onChanged();
      }
      if (!other.getReturnLocation().isEmpty()) {
        returnLocation_ = other.returnLocation_;
        onChanged();
      }
      if (!other.getReturnDate().isEmpty()) {
        returnDate_ = other.returnDate_;
        onChanged();
      }
      if (!other.getReturnTime().isEmpty()) {
        returnTime_ = other.returnTime_;
        onChanged();
      }
      if (!other.getFlightReturnDuration().isEmpty()) {
        flightReturnDuration_ = other.flightReturnDuration_;
        onChanged();
      }
      if (!other.getReturnArrivalTime().isEmpty()) {
        returnArrivalTime_ = other.returnArrivalTime_;
        onChanged();
      }
      if (other.getPassengers() != 0) {
        setPassengers(other.getPassengers());
      }
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.flight.DetailsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.flight.DetailsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object destination_ = "";
    /**
     * <code>string destination = 1;</code>
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination = 1;</code>
     */
    public Builder setDestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 1;</code>
     */
    public Builder clearDestination() {
      
      destination_ = getDefaultInstance().getDestination();
      onChanged();
      return this;
    }
    /**
     * <code>string destination = 1;</code>
     */
    public Builder setDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destination_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object departureDate_ = "";
    /**
     * <code>string departureDate = 2;</code>
     */
    public java.lang.String getDepartureDate() {
      java.lang.Object ref = departureDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departureDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departureDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDepartureDateBytes() {
      java.lang.Object ref = departureDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departureDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departureDate = 2;</code>
     */
    public Builder setDepartureDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departureDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departureDate = 2;</code>
     */
    public Builder clearDepartureDate() {
      
      departureDate_ = getDefaultInstance().getDepartureDate();
      onChanged();
      return this;
    }
    /**
     * <code>string departureDate = 2;</code>
     */
    public Builder setDepartureDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departureDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object departureTime_ = "";
    /**
     * <code>string departureTime = 3;</code>
     */
    public java.lang.String getDepartureTime() {
      java.lang.Object ref = departureTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departureTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departureTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDepartureTimeBytes() {
      java.lang.Object ref = departureTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departureTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departureTime = 3;</code>
     */
    public Builder setDepartureTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departureTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departureTime = 3;</code>
     */
    public Builder clearDepartureTime() {
      
      departureTime_ = getDefaultInstance().getDepartureTime();
      onChanged();
      return this;
    }
    /**
     * <code>string departureTime = 3;</code>
     */
    public Builder setDepartureTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departureTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object flightDuration_ = "";
    /**
     * <code>string flightDuration = 4;</code>
     */
    public java.lang.String getFlightDuration() {
      java.lang.Object ref = flightDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flightDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string flightDuration = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFlightDurationBytes() {
      java.lang.Object ref = flightDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flightDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string flightDuration = 4;</code>
     */
    public Builder setFlightDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      flightDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string flightDuration = 4;</code>
     */
    public Builder clearFlightDuration() {
      
      flightDuration_ = getDefaultInstance().getFlightDuration();
      onChanged();
      return this;
    }
    /**
     * <code>string flightDuration = 4;</code>
     */
    public Builder setFlightDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      flightDuration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrivalTime_ = "";
    /**
     * <code>string arrivalTime = 5;</code>
     */
    public java.lang.String getArrivalTime() {
      java.lang.Object ref = arrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrivalTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalTimeBytes() {
      java.lang.Object ref = arrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrivalTime = 5;</code>
     */
    public Builder setArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalTime = 5;</code>
     */
    public Builder clearArrivalTime() {
      
      arrivalTime_ = getDefaultInstance().getArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalTime = 5;</code>
     */
    public Builder setArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrivalTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object flightNumber_ = "";
    /**
     * <code>string flightNumber = 6;</code>
     */
    public java.lang.String getFlightNumber() {
      java.lang.Object ref = flightNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flightNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string flightNumber = 6;</code>
     */
    public com.google.protobuf.ByteString
        getFlightNumberBytes() {
      java.lang.Object ref = flightNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flightNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string flightNumber = 6;</code>
     */
    public Builder setFlightNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      flightNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string flightNumber = 6;</code>
     */
    public Builder clearFlightNumber() {
      
      flightNumber_ = getDefaultInstance().getFlightNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string flightNumber = 6;</code>
     */
    public Builder setFlightNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      flightNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnLocation_ = "";
    /**
     * <code>string returnLocation = 7;</code>
     */
    public java.lang.String getReturnLocation() {
      java.lang.Object ref = returnLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnLocation = 7;</code>
     */
    public com.google.protobuf.ByteString
        getReturnLocationBytes() {
      java.lang.Object ref = returnLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnLocation = 7;</code>
     */
    public Builder setReturnLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string returnLocation = 7;</code>
     */
    public Builder clearReturnLocation() {
      
      returnLocation_ = getDefaultInstance().getReturnLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string returnLocation = 7;</code>
     */
    public Builder setReturnLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnLocation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnDate_ = "";
    /**
     * <code>string returnDate = 8;</code>
     */
    public java.lang.String getReturnDate() {
      java.lang.Object ref = returnDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnDate = 8;</code>
     */
    public com.google.protobuf.ByteString
        getReturnDateBytes() {
      java.lang.Object ref = returnDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnDate = 8;</code>
     */
    public Builder setReturnDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string returnDate = 8;</code>
     */
    public Builder clearReturnDate() {
      
      returnDate_ = getDefaultInstance().getReturnDate();
      onChanged();
      return this;
    }
    /**
     * <code>string returnDate = 8;</code>
     */
    public Builder setReturnDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnTime_ = "";
    /**
     * <code>string returnTime = 9;</code>
     */
    public java.lang.String getReturnTime() {
      java.lang.Object ref = returnTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnTime = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReturnTimeBytes() {
      java.lang.Object ref = returnTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnTime = 9;</code>
     */
    public Builder setReturnTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string returnTime = 9;</code>
     */
    public Builder clearReturnTime() {
      
      returnTime_ = getDefaultInstance().getReturnTime();
      onChanged();
      return this;
    }
    /**
     * <code>string returnTime = 9;</code>
     */
    public Builder setReturnTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object flightReturnDuration_ = "";
    /**
     * <code>string flightReturnDuration = 10;</code>
     */
    public java.lang.String getFlightReturnDuration() {
      java.lang.Object ref = flightReturnDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flightReturnDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string flightReturnDuration = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFlightReturnDurationBytes() {
      java.lang.Object ref = flightReturnDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flightReturnDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string flightReturnDuration = 10;</code>
     */
    public Builder setFlightReturnDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      flightReturnDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string flightReturnDuration = 10;</code>
     */
    public Builder clearFlightReturnDuration() {
      
      flightReturnDuration_ = getDefaultInstance().getFlightReturnDuration();
      onChanged();
      return this;
    }
    /**
     * <code>string flightReturnDuration = 10;</code>
     */
    public Builder setFlightReturnDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      flightReturnDuration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object returnArrivalTime_ = "";
    /**
     * <code>string returnArrivalTime = 11;</code>
     */
    public java.lang.String getReturnArrivalTime() {
      java.lang.Object ref = returnArrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnArrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnArrivalTime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getReturnArrivalTimeBytes() {
      java.lang.Object ref = returnArrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnArrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnArrivalTime = 11;</code>
     */
    public Builder setReturnArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      returnArrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string returnArrivalTime = 11;</code>
     */
    public Builder clearReturnArrivalTime() {
      
      returnArrivalTime_ = getDefaultInstance().getReturnArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string returnArrivalTime = 11;</code>
     */
    public Builder setReturnArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      returnArrivalTime_ = value;
      onChanged();
      return this;
    }

    private int passengers_ ;
    /**
     * <code>int32 passengers = 12;</code>
     */
    public int getPassengers() {
      return passengers_;
    }
    /**
     * <code>int32 passengers = 12;</code>
     */
    public Builder setPassengers(int value) {
      
      passengers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 passengers = 12;</code>
     */
    public Builder clearPassengers() {
      
      passengers_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object price_ = "";
    /**
     * <code>string price = 13;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string price = 13;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string price = 13;</code>
     */
    public Builder setPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string price = 13;</code>
     */
    public Builder clearPrice() {
      
      price_ = getDefaultInstance().getPrice();
      onChanged();
      return this;
    }
    /**
     * <code>string price = 13;</code>
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      price_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.flight.DetailsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.flight.DetailsResponse)
  private static final com.alexeyre.grpc.flight.DetailsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.flight.DetailsResponse();
  }

  public static com.alexeyre.grpc.flight.DetailsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DetailsResponse>
      PARSER = new com.google.protobuf.AbstractParser<DetailsResponse>() {
    @java.lang.Override
    public DetailsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DetailsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DetailsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DetailsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.flight.DetailsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

