// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

/**
 * Protobuf type {@code com.alexeyre.grpc.flight.DisplayResponse}
 */
public  final class DisplayResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.flight.DisplayResponse)
    DisplayResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DisplayResponse.newBuilder() to construct.
  private DisplayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DisplayResponse() {
    displayDestination_ = "";
    displayDepartureDate_ = "";
    displayDepartureTime_ = "";
    displayFlightDuration_ = "";
    displayArrivalTime_ = "";
    displayFlightId_ = "";
    displayReturnLocation_ = "";
    displayReturnDate_ = "";
    displayReturnTime_ = "";
    displayFlightReturnDuration_ = "";
    displayReturnArrivalTime_ = "";
    displayPassengers_ = 0;
    displayPrice_ = "";
    displayTicketType_ = "";
    displaySeatPref_ = "";
    displayFirstname_ = "";
    displaySurname_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DisplayResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            displayDestination_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            displayDepartureDate_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            displayDepartureTime_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            displayFlightDuration_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            displayArrivalTime_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            displayFlightId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            displayReturnLocation_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            displayReturnDate_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            displayReturnTime_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            displayFlightReturnDuration_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            displayReturnArrivalTime_ = s;
            break;
          }
          case 96: {

            displayPassengers_ = input.readInt32();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            displayPrice_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            displayTicketType_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            displaySeatPref_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            displayFirstname_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            displaySurname_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DisplayResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DisplayResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.flight.DisplayResponse.class, com.alexeyre.grpc.flight.DisplayResponse.Builder.class);
  }

  public static final int DISPLAYDESTINATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object displayDestination_;
  /**
   * <code>string displayDestination = 1;</code>
   */
  public java.lang.String getDisplayDestination() {
    java.lang.Object ref = displayDestination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayDestination_ = s;
      return s;
    }
  }
  /**
   * <code>string displayDestination = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayDestinationBytes() {
    java.lang.Object ref = displayDestination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayDestination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYDEPARTUREDATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object displayDepartureDate_;
  /**
   * <code>string displayDepartureDate = 2;</code>
   */
  public java.lang.String getDisplayDepartureDate() {
    java.lang.Object ref = displayDepartureDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayDepartureDate_ = s;
      return s;
    }
  }
  /**
   * <code>string displayDepartureDate = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayDepartureDateBytes() {
    java.lang.Object ref = displayDepartureDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayDepartureDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYDEPARTURETIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object displayDepartureTime_;
  /**
   * <code>string displayDepartureTime = 3;</code>
   */
  public java.lang.String getDisplayDepartureTime() {
    java.lang.Object ref = displayDepartureTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayDepartureTime_ = s;
      return s;
    }
  }
  /**
   * <code>string displayDepartureTime = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayDepartureTimeBytes() {
    java.lang.Object ref = displayDepartureTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayDepartureTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYFLIGHTDURATION_FIELD_NUMBER = 4;
  private volatile java.lang.Object displayFlightDuration_;
  /**
   * <code>string displayFlightDuration = 4;</code>
   */
  public java.lang.String getDisplayFlightDuration() {
    java.lang.Object ref = displayFlightDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayFlightDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string displayFlightDuration = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayFlightDurationBytes() {
    java.lang.Object ref = displayFlightDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayFlightDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYARRIVALTIME_FIELD_NUMBER = 5;
  private volatile java.lang.Object displayArrivalTime_;
  /**
   * <code>string displayArrivalTime = 5;</code>
   */
  public java.lang.String getDisplayArrivalTime() {
    java.lang.Object ref = displayArrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayArrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string displayArrivalTime = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayArrivalTimeBytes() {
    java.lang.Object ref = displayArrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayArrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYFLIGHTID_FIELD_NUMBER = 6;
  private volatile java.lang.Object displayFlightId_;
  /**
   * <code>string displayFlightId = 6;</code>
   */
  public java.lang.String getDisplayFlightId() {
    java.lang.Object ref = displayFlightId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayFlightId_ = s;
      return s;
    }
  }
  /**
   * <code>string displayFlightId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayFlightIdBytes() {
    java.lang.Object ref = displayFlightId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayFlightId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYRETURNLOCATION_FIELD_NUMBER = 7;
  private volatile java.lang.Object displayReturnLocation_;
  /**
   * <code>string displayReturnLocation = 7;</code>
   */
  public java.lang.String getDisplayReturnLocation() {
    java.lang.Object ref = displayReturnLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayReturnLocation_ = s;
      return s;
    }
  }
  /**
   * <code>string displayReturnLocation = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayReturnLocationBytes() {
    java.lang.Object ref = displayReturnLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayReturnLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYRETURNDATE_FIELD_NUMBER = 8;
  private volatile java.lang.Object displayReturnDate_;
  /**
   * <code>string displayReturnDate = 8;</code>
   */
  public java.lang.String getDisplayReturnDate() {
    java.lang.Object ref = displayReturnDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayReturnDate_ = s;
      return s;
    }
  }
  /**
   * <code>string displayReturnDate = 8;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayReturnDateBytes() {
    java.lang.Object ref = displayReturnDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayReturnDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYRETURNTIME_FIELD_NUMBER = 9;
  private volatile java.lang.Object displayReturnTime_;
  /**
   * <code>string displayReturnTime = 9;</code>
   */
  public java.lang.String getDisplayReturnTime() {
    java.lang.Object ref = displayReturnTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayReturnTime_ = s;
      return s;
    }
  }
  /**
   * <code>string displayReturnTime = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayReturnTimeBytes() {
    java.lang.Object ref = displayReturnTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayReturnTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYFLIGHTRETURNDURATION_FIELD_NUMBER = 10;
  private volatile java.lang.Object displayFlightReturnDuration_;
  /**
   * <code>string displayFlightReturnDuration = 10;</code>
   */
  public java.lang.String getDisplayFlightReturnDuration() {
    java.lang.Object ref = displayFlightReturnDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayFlightReturnDuration_ = s;
      return s;
    }
  }
  /**
   * <code>string displayFlightReturnDuration = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayFlightReturnDurationBytes() {
    java.lang.Object ref = displayFlightReturnDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayFlightReturnDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYRETURNARRIVALTIME_FIELD_NUMBER = 11;
  private volatile java.lang.Object displayReturnArrivalTime_;
  /**
   * <code>string displayReturnArrivalTime = 11;</code>
   */
  public java.lang.String getDisplayReturnArrivalTime() {
    java.lang.Object ref = displayReturnArrivalTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayReturnArrivalTime_ = s;
      return s;
    }
  }
  /**
   * <code>string displayReturnArrivalTime = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayReturnArrivalTimeBytes() {
    java.lang.Object ref = displayReturnArrivalTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayReturnArrivalTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYPASSENGERS_FIELD_NUMBER = 12;
  private int displayPassengers_;
  /**
   * <code>int32 displayPassengers = 12;</code>
   */
  public int getDisplayPassengers() {
    return displayPassengers_;
  }

  public static final int DISPLAYPRICE_FIELD_NUMBER = 13;
  private volatile java.lang.Object displayPrice_;
  /**
   * <code>string displayPrice = 13;</code>
   */
  public java.lang.String getDisplayPrice() {
    java.lang.Object ref = displayPrice_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayPrice_ = s;
      return s;
    }
  }
  /**
   * <code>string displayPrice = 13;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayPriceBytes() {
    java.lang.Object ref = displayPrice_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayPrice_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYTICKETTYPE_FIELD_NUMBER = 14;
  private volatile java.lang.Object displayTicketType_;
  /**
   * <code>string displayTicketType = 14;</code>
   */
  public java.lang.String getDisplayTicketType() {
    java.lang.Object ref = displayTicketType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayTicketType_ = s;
      return s;
    }
  }
  /**
   * <code>string displayTicketType = 14;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayTicketTypeBytes() {
    java.lang.Object ref = displayTicketType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayTicketType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYSEATPREF_FIELD_NUMBER = 15;
  private volatile java.lang.Object displaySeatPref_;
  /**
   * <code>string displaySeatPref = 15;</code>
   */
  public java.lang.String getDisplaySeatPref() {
    java.lang.Object ref = displaySeatPref_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displaySeatPref_ = s;
      return s;
    }
  }
  /**
   * <code>string displaySeatPref = 15;</code>
   */
  public com.google.protobuf.ByteString
      getDisplaySeatPrefBytes() {
    java.lang.Object ref = displaySeatPref_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displaySeatPref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYFIRSTNAME_FIELD_NUMBER = 16;
  private volatile java.lang.Object displayFirstname_;
  /**
   * <code>string displayFirstname = 16;</code>
   */
  public java.lang.String getDisplayFirstname() {
    java.lang.Object ref = displayFirstname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayFirstname_ = s;
      return s;
    }
  }
  /**
   * <code>string displayFirstname = 16;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayFirstnameBytes() {
    java.lang.Object ref = displayFirstname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayFirstname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYSURNAME_FIELD_NUMBER = 17;
  private volatile java.lang.Object displaySurname_;
  /**
   * <code>string displaySurname = 17;</code>
   */
  public java.lang.String getDisplaySurname() {
    java.lang.Object ref = displaySurname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displaySurname_ = s;
      return s;
    }
  }
  /**
   * <code>string displaySurname = 17;</code>
   */
  public com.google.protobuf.ByteString
      getDisplaySurnameBytes() {
    java.lang.Object ref = displaySurname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displaySurname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDisplayDestinationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, displayDestination_);
    }
    if (!getDisplayDepartureDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, displayDepartureDate_);
    }
    if (!getDisplayDepartureTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, displayDepartureTime_);
    }
    if (!getDisplayFlightDurationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, displayFlightDuration_);
    }
    if (!getDisplayArrivalTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, displayArrivalTime_);
    }
    if (!getDisplayFlightIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, displayFlightId_);
    }
    if (!getDisplayReturnLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, displayReturnLocation_);
    }
    if (!getDisplayReturnDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, displayReturnDate_);
    }
    if (!getDisplayReturnTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, displayReturnTime_);
    }
    if (!getDisplayFlightReturnDurationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, displayFlightReturnDuration_);
    }
    if (!getDisplayReturnArrivalTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, displayReturnArrivalTime_);
    }
    if (displayPassengers_ != 0) {
      output.writeInt32(12, displayPassengers_);
    }
    if (!getDisplayPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, displayPrice_);
    }
    if (!getDisplayTicketTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, displayTicketType_);
    }
    if (!getDisplaySeatPrefBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, displaySeatPref_);
    }
    if (!getDisplayFirstnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, displayFirstname_);
    }
    if (!getDisplaySurnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, displaySurname_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDisplayDestinationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, displayDestination_);
    }
    if (!getDisplayDepartureDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, displayDepartureDate_);
    }
    if (!getDisplayDepartureTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, displayDepartureTime_);
    }
    if (!getDisplayFlightDurationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, displayFlightDuration_);
    }
    if (!getDisplayArrivalTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, displayArrivalTime_);
    }
    if (!getDisplayFlightIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, displayFlightId_);
    }
    if (!getDisplayReturnLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, displayReturnLocation_);
    }
    if (!getDisplayReturnDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, displayReturnDate_);
    }
    if (!getDisplayReturnTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, displayReturnTime_);
    }
    if (!getDisplayFlightReturnDurationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, displayFlightReturnDuration_);
    }
    if (!getDisplayReturnArrivalTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, displayReturnArrivalTime_);
    }
    if (displayPassengers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, displayPassengers_);
    }
    if (!getDisplayPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, displayPrice_);
    }
    if (!getDisplayTicketTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, displayTicketType_);
    }
    if (!getDisplaySeatPrefBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, displaySeatPref_);
    }
    if (!getDisplayFirstnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, displayFirstname_);
    }
    if (!getDisplaySurnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, displaySurname_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.flight.DisplayResponse)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.flight.DisplayResponse other = (com.alexeyre.grpc.flight.DisplayResponse) obj;

    boolean result = true;
    result = result && getDisplayDestination()
        .equals(other.getDisplayDestination());
    result = result && getDisplayDepartureDate()
        .equals(other.getDisplayDepartureDate());
    result = result && getDisplayDepartureTime()
        .equals(other.getDisplayDepartureTime());
    result = result && getDisplayFlightDuration()
        .equals(other.getDisplayFlightDuration());
    result = result && getDisplayArrivalTime()
        .equals(other.getDisplayArrivalTime());
    result = result && getDisplayFlightId()
        .equals(other.getDisplayFlightId());
    result = result && getDisplayReturnLocation()
        .equals(other.getDisplayReturnLocation());
    result = result && getDisplayReturnDate()
        .equals(other.getDisplayReturnDate());
    result = result && getDisplayReturnTime()
        .equals(other.getDisplayReturnTime());
    result = result && getDisplayFlightReturnDuration()
        .equals(other.getDisplayFlightReturnDuration());
    result = result && getDisplayReturnArrivalTime()
        .equals(other.getDisplayReturnArrivalTime());
    result = result && (getDisplayPassengers()
        == other.getDisplayPassengers());
    result = result && getDisplayPrice()
        .equals(other.getDisplayPrice());
    result = result && getDisplayTicketType()
        .equals(other.getDisplayTicketType());
    result = result && getDisplaySeatPref()
        .equals(other.getDisplaySeatPref());
    result = result && getDisplayFirstname()
        .equals(other.getDisplayFirstname());
    result = result && getDisplaySurname()
        .equals(other.getDisplaySurname());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAYDESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayDestination().hashCode();
    hash = (37 * hash) + DISPLAYDEPARTUREDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayDepartureDate().hashCode();
    hash = (37 * hash) + DISPLAYDEPARTURETIME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayDepartureTime().hashCode();
    hash = (37 * hash) + DISPLAYFLIGHTDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayFlightDuration().hashCode();
    hash = (37 * hash) + DISPLAYARRIVALTIME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayArrivalTime().hashCode();
    hash = (37 * hash) + DISPLAYFLIGHTID_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayFlightId().hashCode();
    hash = (37 * hash) + DISPLAYRETURNLOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayReturnLocation().hashCode();
    hash = (37 * hash) + DISPLAYRETURNDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayReturnDate().hashCode();
    hash = (37 * hash) + DISPLAYRETURNTIME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayReturnTime().hashCode();
    hash = (37 * hash) + DISPLAYFLIGHTRETURNDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayFlightReturnDuration().hashCode();
    hash = (37 * hash) + DISPLAYRETURNARRIVALTIME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayReturnArrivalTime().hashCode();
    hash = (37 * hash) + DISPLAYPASSENGERS_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayPassengers();
    hash = (37 * hash) + DISPLAYPRICE_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayPrice().hashCode();
    hash = (37 * hash) + DISPLAYTICKETTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayTicketType().hashCode();
    hash = (37 * hash) + DISPLAYSEATPREF_FIELD_NUMBER;
    hash = (53 * hash) + getDisplaySeatPref().hashCode();
    hash = (37 * hash) + DISPLAYFIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayFirstname().hashCode();
    hash = (37 * hash) + DISPLAYSURNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDisplaySurname().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.DisplayResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.flight.DisplayResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.flight.DisplayResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.flight.DisplayResponse)
      com.alexeyre.grpc.flight.DisplayResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DisplayResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DisplayResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.flight.DisplayResponse.class, com.alexeyre.grpc.flight.DisplayResponse.Builder.class);
    }

    // Construct using com.alexeyre.grpc.flight.DisplayResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      displayDestination_ = "";

      displayDepartureDate_ = "";

      displayDepartureTime_ = "";

      displayFlightDuration_ = "";

      displayArrivalTime_ = "";

      displayFlightId_ = "";

      displayReturnLocation_ = "";

      displayReturnDate_ = "";

      displayReturnTime_ = "";

      displayFlightReturnDuration_ = "";

      displayReturnArrivalTime_ = "";

      displayPassengers_ = 0;

      displayPrice_ = "";

      displayTicketType_ = "";

      displaySeatPref_ = "";

      displayFirstname_ = "";

      displaySurname_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_DisplayResponse_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DisplayResponse getDefaultInstanceForType() {
      return com.alexeyre.grpc.flight.DisplayResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DisplayResponse build() {
      com.alexeyre.grpc.flight.DisplayResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.DisplayResponse buildPartial() {
      com.alexeyre.grpc.flight.DisplayResponse result = new com.alexeyre.grpc.flight.DisplayResponse(this);
      result.displayDestination_ = displayDestination_;
      result.displayDepartureDate_ = displayDepartureDate_;
      result.displayDepartureTime_ = displayDepartureTime_;
      result.displayFlightDuration_ = displayFlightDuration_;
      result.displayArrivalTime_ = displayArrivalTime_;
      result.displayFlightId_ = displayFlightId_;
      result.displayReturnLocation_ = displayReturnLocation_;
      result.displayReturnDate_ = displayReturnDate_;
      result.displayReturnTime_ = displayReturnTime_;
      result.displayFlightReturnDuration_ = displayFlightReturnDuration_;
      result.displayReturnArrivalTime_ = displayReturnArrivalTime_;
      result.displayPassengers_ = displayPassengers_;
      result.displayPrice_ = displayPrice_;
      result.displayTicketType_ = displayTicketType_;
      result.displaySeatPref_ = displaySeatPref_;
      result.displayFirstname_ = displayFirstname_;
      result.displaySurname_ = displaySurname_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.flight.DisplayResponse) {
        return mergeFrom((com.alexeyre.grpc.flight.DisplayResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.flight.DisplayResponse other) {
      if (other == com.alexeyre.grpc.flight.DisplayResponse.getDefaultInstance()) return this;
      if (!other.getDisplayDestination().isEmpty()) {
        displayDestination_ = other.displayDestination_;
        onChanged();
      }
      if (!other.getDisplayDepartureDate().isEmpty()) {
        displayDepartureDate_ = other.displayDepartureDate_;
        onChanged();
      }
      if (!other.getDisplayDepartureTime().isEmpty()) {
        displayDepartureTime_ = other.displayDepartureTime_;
        onChanged();
      }
      if (!other.getDisplayFlightDuration().isEmpty()) {
        displayFlightDuration_ = other.displayFlightDuration_;
        onChanged();
      }
      if (!other.getDisplayArrivalTime().isEmpty()) {
        displayArrivalTime_ = other.displayArrivalTime_;
        onChanged();
      }
      if (!other.getDisplayFlightId().isEmpty()) {
        displayFlightId_ = other.displayFlightId_;
        onChanged();
      }
      if (!other.getDisplayReturnLocation().isEmpty()) {
        displayReturnLocation_ = other.displayReturnLocation_;
        onChanged();
      }
      if (!other.getDisplayReturnDate().isEmpty()) {
        displayReturnDate_ = other.displayReturnDate_;
        onChanged();
      }
      if (!other.getDisplayReturnTime().isEmpty()) {
        displayReturnTime_ = other.displayReturnTime_;
        onChanged();
      }
      if (!other.getDisplayFlightReturnDuration().isEmpty()) {
        displayFlightReturnDuration_ = other.displayFlightReturnDuration_;
        onChanged();
      }
      if (!other.getDisplayReturnArrivalTime().isEmpty()) {
        displayReturnArrivalTime_ = other.displayReturnArrivalTime_;
        onChanged();
      }
      if (other.getDisplayPassengers() != 0) {
        setDisplayPassengers(other.getDisplayPassengers());
      }
      if (!other.getDisplayPrice().isEmpty()) {
        displayPrice_ = other.displayPrice_;
        onChanged();
      }
      if (!other.getDisplayTicketType().isEmpty()) {
        displayTicketType_ = other.displayTicketType_;
        onChanged();
      }
      if (!other.getDisplaySeatPref().isEmpty()) {
        displaySeatPref_ = other.displaySeatPref_;
        onChanged();
      }
      if (!other.getDisplayFirstname().isEmpty()) {
        displayFirstname_ = other.displayFirstname_;
        onChanged();
      }
      if (!other.getDisplaySurname().isEmpty()) {
        displaySurname_ = other.displaySurname_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.flight.DisplayResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.flight.DisplayResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object displayDestination_ = "";
    /**
     * <code>string displayDestination = 1;</code>
     */
    public java.lang.String getDisplayDestination() {
      java.lang.Object ref = displayDestination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayDestination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayDestination = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayDestinationBytes() {
      java.lang.Object ref = displayDestination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayDestination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayDestination = 1;</code>
     */
    public Builder setDisplayDestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayDestination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayDestination = 1;</code>
     */
    public Builder clearDisplayDestination() {
      
      displayDestination_ = getDefaultInstance().getDisplayDestination();
      onChanged();
      return this;
    }
    /**
     * <code>string displayDestination = 1;</code>
     */
    public Builder setDisplayDestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayDestination_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayDepartureDate_ = "";
    /**
     * <code>string displayDepartureDate = 2;</code>
     */
    public java.lang.String getDisplayDepartureDate() {
      java.lang.Object ref = displayDepartureDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayDepartureDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayDepartureDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayDepartureDateBytes() {
      java.lang.Object ref = displayDepartureDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayDepartureDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayDepartureDate = 2;</code>
     */
    public Builder setDisplayDepartureDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayDepartureDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayDepartureDate = 2;</code>
     */
    public Builder clearDisplayDepartureDate() {
      
      displayDepartureDate_ = getDefaultInstance().getDisplayDepartureDate();
      onChanged();
      return this;
    }
    /**
     * <code>string displayDepartureDate = 2;</code>
     */
    public Builder setDisplayDepartureDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayDepartureDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayDepartureTime_ = "";
    /**
     * <code>string displayDepartureTime = 3;</code>
     */
    public java.lang.String getDisplayDepartureTime() {
      java.lang.Object ref = displayDepartureTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayDepartureTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayDepartureTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayDepartureTimeBytes() {
      java.lang.Object ref = displayDepartureTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayDepartureTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayDepartureTime = 3;</code>
     */
    public Builder setDisplayDepartureTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayDepartureTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayDepartureTime = 3;</code>
     */
    public Builder clearDisplayDepartureTime() {
      
      displayDepartureTime_ = getDefaultInstance().getDisplayDepartureTime();
      onChanged();
      return this;
    }
    /**
     * <code>string displayDepartureTime = 3;</code>
     */
    public Builder setDisplayDepartureTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayDepartureTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayFlightDuration_ = "";
    /**
     * <code>string displayFlightDuration = 4;</code>
     */
    public java.lang.String getDisplayFlightDuration() {
      java.lang.Object ref = displayFlightDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayFlightDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayFlightDuration = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayFlightDurationBytes() {
      java.lang.Object ref = displayFlightDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayFlightDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayFlightDuration = 4;</code>
     */
    public Builder setDisplayFlightDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayFlightDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightDuration = 4;</code>
     */
    public Builder clearDisplayFlightDuration() {
      
      displayFlightDuration_ = getDefaultInstance().getDisplayFlightDuration();
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightDuration = 4;</code>
     */
    public Builder setDisplayFlightDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayFlightDuration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayArrivalTime_ = "";
    /**
     * <code>string displayArrivalTime = 5;</code>
     */
    public java.lang.String getDisplayArrivalTime() {
      java.lang.Object ref = displayArrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayArrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayArrivalTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayArrivalTimeBytes() {
      java.lang.Object ref = displayArrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayArrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayArrivalTime = 5;</code>
     */
    public Builder setDisplayArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayArrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayArrivalTime = 5;</code>
     */
    public Builder clearDisplayArrivalTime() {
      
      displayArrivalTime_ = getDefaultInstance().getDisplayArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string displayArrivalTime = 5;</code>
     */
    public Builder setDisplayArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayArrivalTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayFlightId_ = "";
    /**
     * <code>string displayFlightId = 6;</code>
     */
    public java.lang.String getDisplayFlightId() {
      java.lang.Object ref = displayFlightId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayFlightId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayFlightId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayFlightIdBytes() {
      java.lang.Object ref = displayFlightId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayFlightId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayFlightId = 6;</code>
     */
    public Builder setDisplayFlightId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayFlightId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightId = 6;</code>
     */
    public Builder clearDisplayFlightId() {
      
      displayFlightId_ = getDefaultInstance().getDisplayFlightId();
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightId = 6;</code>
     */
    public Builder setDisplayFlightIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayFlightId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayReturnLocation_ = "";
    /**
     * <code>string displayReturnLocation = 7;</code>
     */
    public java.lang.String getDisplayReturnLocation() {
      java.lang.Object ref = displayReturnLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayReturnLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayReturnLocation = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayReturnLocationBytes() {
      java.lang.Object ref = displayReturnLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayReturnLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayReturnLocation = 7;</code>
     */
    public Builder setDisplayReturnLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayReturnLocation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnLocation = 7;</code>
     */
    public Builder clearDisplayReturnLocation() {
      
      displayReturnLocation_ = getDefaultInstance().getDisplayReturnLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnLocation = 7;</code>
     */
    public Builder setDisplayReturnLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayReturnLocation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayReturnDate_ = "";
    /**
     * <code>string displayReturnDate = 8;</code>
     */
    public java.lang.String getDisplayReturnDate() {
      java.lang.Object ref = displayReturnDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayReturnDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayReturnDate = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayReturnDateBytes() {
      java.lang.Object ref = displayReturnDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayReturnDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayReturnDate = 8;</code>
     */
    public Builder setDisplayReturnDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayReturnDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnDate = 8;</code>
     */
    public Builder clearDisplayReturnDate() {
      
      displayReturnDate_ = getDefaultInstance().getDisplayReturnDate();
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnDate = 8;</code>
     */
    public Builder setDisplayReturnDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayReturnDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayReturnTime_ = "";
    /**
     * <code>string displayReturnTime = 9;</code>
     */
    public java.lang.String getDisplayReturnTime() {
      java.lang.Object ref = displayReturnTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayReturnTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayReturnTime = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayReturnTimeBytes() {
      java.lang.Object ref = displayReturnTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayReturnTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayReturnTime = 9;</code>
     */
    public Builder setDisplayReturnTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayReturnTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnTime = 9;</code>
     */
    public Builder clearDisplayReturnTime() {
      
      displayReturnTime_ = getDefaultInstance().getDisplayReturnTime();
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnTime = 9;</code>
     */
    public Builder setDisplayReturnTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayReturnTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayFlightReturnDuration_ = "";
    /**
     * <code>string displayFlightReturnDuration = 10;</code>
     */
    public java.lang.String getDisplayFlightReturnDuration() {
      java.lang.Object ref = displayFlightReturnDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayFlightReturnDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayFlightReturnDuration = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayFlightReturnDurationBytes() {
      java.lang.Object ref = displayFlightReturnDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayFlightReturnDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayFlightReturnDuration = 10;</code>
     */
    public Builder setDisplayFlightReturnDuration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayFlightReturnDuration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightReturnDuration = 10;</code>
     */
    public Builder clearDisplayFlightReturnDuration() {
      
      displayFlightReturnDuration_ = getDefaultInstance().getDisplayFlightReturnDuration();
      onChanged();
      return this;
    }
    /**
     * <code>string displayFlightReturnDuration = 10;</code>
     */
    public Builder setDisplayFlightReturnDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayFlightReturnDuration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayReturnArrivalTime_ = "";
    /**
     * <code>string displayReturnArrivalTime = 11;</code>
     */
    public java.lang.String getDisplayReturnArrivalTime() {
      java.lang.Object ref = displayReturnArrivalTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayReturnArrivalTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayReturnArrivalTime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayReturnArrivalTimeBytes() {
      java.lang.Object ref = displayReturnArrivalTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayReturnArrivalTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayReturnArrivalTime = 11;</code>
     */
    public Builder setDisplayReturnArrivalTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayReturnArrivalTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnArrivalTime = 11;</code>
     */
    public Builder clearDisplayReturnArrivalTime() {
      
      displayReturnArrivalTime_ = getDefaultInstance().getDisplayReturnArrivalTime();
      onChanged();
      return this;
    }
    /**
     * <code>string displayReturnArrivalTime = 11;</code>
     */
    public Builder setDisplayReturnArrivalTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayReturnArrivalTime_ = value;
      onChanged();
      return this;
    }

    private int displayPassengers_ ;
    /**
     * <code>int32 displayPassengers = 12;</code>
     */
    public int getDisplayPassengers() {
      return displayPassengers_;
    }
    /**
     * <code>int32 displayPassengers = 12;</code>
     */
    public Builder setDisplayPassengers(int value) {
      
      displayPassengers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 displayPassengers = 12;</code>
     */
    public Builder clearDisplayPassengers() {
      
      displayPassengers_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object displayPrice_ = "";
    /**
     * <code>string displayPrice = 13;</code>
     */
    public java.lang.String getDisplayPrice() {
      java.lang.Object ref = displayPrice_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayPrice_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayPrice = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayPriceBytes() {
      java.lang.Object ref = displayPrice_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayPrice = 13;</code>
     */
    public Builder setDisplayPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayPrice = 13;</code>
     */
    public Builder clearDisplayPrice() {
      
      displayPrice_ = getDefaultInstance().getDisplayPrice();
      onChanged();
      return this;
    }
    /**
     * <code>string displayPrice = 13;</code>
     */
    public Builder setDisplayPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayPrice_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayTicketType_ = "";
    /**
     * <code>string displayTicketType = 14;</code>
     */
    public java.lang.String getDisplayTicketType() {
      java.lang.Object ref = displayTicketType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayTicketType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayTicketType = 14;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayTicketTypeBytes() {
      java.lang.Object ref = displayTicketType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayTicketType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayTicketType = 14;</code>
     */
    public Builder setDisplayTicketType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayTicketType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayTicketType = 14;</code>
     */
    public Builder clearDisplayTicketType() {
      
      displayTicketType_ = getDefaultInstance().getDisplayTicketType();
      onChanged();
      return this;
    }
    /**
     * <code>string displayTicketType = 14;</code>
     */
    public Builder setDisplayTicketTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayTicketType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displaySeatPref_ = "";
    /**
     * <code>string displaySeatPref = 15;</code>
     */
    public java.lang.String getDisplaySeatPref() {
      java.lang.Object ref = displaySeatPref_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displaySeatPref_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displaySeatPref = 15;</code>
     */
    public com.google.protobuf.ByteString
        getDisplaySeatPrefBytes() {
      java.lang.Object ref = displaySeatPref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displaySeatPref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displaySeatPref = 15;</code>
     */
    public Builder setDisplaySeatPref(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displaySeatPref_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displaySeatPref = 15;</code>
     */
    public Builder clearDisplaySeatPref() {
      
      displaySeatPref_ = getDefaultInstance().getDisplaySeatPref();
      onChanged();
      return this;
    }
    /**
     * <code>string displaySeatPref = 15;</code>
     */
    public Builder setDisplaySeatPrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displaySeatPref_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displayFirstname_ = "";
    /**
     * <code>string displayFirstname = 16;</code>
     */
    public java.lang.String getDisplayFirstname() {
      java.lang.Object ref = displayFirstname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayFirstname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displayFirstname = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayFirstnameBytes() {
      java.lang.Object ref = displayFirstname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayFirstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displayFirstname = 16;</code>
     */
    public Builder setDisplayFirstname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayFirstname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displayFirstname = 16;</code>
     */
    public Builder clearDisplayFirstname() {
      
      displayFirstname_ = getDefaultInstance().getDisplayFirstname();
      onChanged();
      return this;
    }
    /**
     * <code>string displayFirstname = 16;</code>
     */
    public Builder setDisplayFirstnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayFirstname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object displaySurname_ = "";
    /**
     * <code>string displaySurname = 17;</code>
     */
    public java.lang.String getDisplaySurname() {
      java.lang.Object ref = displaySurname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displaySurname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string displaySurname = 17;</code>
     */
    public com.google.protobuf.ByteString
        getDisplaySurnameBytes() {
      java.lang.Object ref = displaySurname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displaySurname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string displaySurname = 17;</code>
     */
    public Builder setDisplaySurname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displaySurname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string displaySurname = 17;</code>
     */
    public Builder clearDisplaySurname() {
      
      displaySurname_ = getDefaultInstance().getDisplaySurname();
      onChanged();
      return this;
    }
    /**
     * <code>string displaySurname = 17;</code>
     */
    public Builder setDisplaySurnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displaySurname_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.flight.DisplayResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.flight.DisplayResponse)
  private static final com.alexeyre.grpc.flight.DisplayResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.flight.DisplayResponse();
  }

  public static com.alexeyre.grpc.flight.DisplayResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DisplayResponse>
      PARSER = new com.google.protobuf.AbstractParser<DisplayResponse>() {
    @java.lang.Override
    public DisplayResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DisplayResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DisplayResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DisplayResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.flight.DisplayResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

