// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface DisplayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.DisplayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string displayRequest = 1;</code>
   */
  java.lang.String getDisplayRequest();
  /**
   * <code>string displayRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getDisplayRequestBytes();
}
