// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public final class FlightServiceImpl {
  private FlightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_BookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PeopleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PassengerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PassengerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014flight.proto\022\030com.alexeyre.grpc.flight" +
      "\"Y\n\013ListRequest\022\021\n\tlocation1\030\001 \001(\t\022\021\n\tlo" +
      "cation2\030\002 \001(\t\022\021\n\tlocation3\030\003 \001(\t\022\021\n\tloca" +
      "tion4\030\004 \001(\t\"\036\n\014ListResponse\022\016\n\006result\030\001 " +
      "\001(\t\"\037\n\016BookingRequest\022\r\n\005value\030\001 \001(\t\"\212\001\n" +
      "\017BookingResponse\022\024\n\014responseCode\030\001 \001(\005\022\027" +
      "\n\017responseMessage\030\002 \001(\t\022\016\n\006depart\030\003 \001(\t\022" +
      "\022\n\ndepartDate\030\004 \001(\t\022\017\n\007arrival\030\005 \001(\t\022\023\n\013" +
      "arrivalDate\030\006 \001(\t\"#\n\rPeopleRequest\022\022\n\npa" +
      "ssengers\030\001 \001(\005\"$\n\016PeopleResponse\022\022\n\npass" +
      "engers\030\001 \001(\005\"1\n\020PassengerRequest\022\014\n\004seat" +
      "\030\001 \001(\t\022\017\n\007luggage\030\002 \001(\005\"2\n\021PassengerResp" +
      "onse\022\014\n\004seat\030\001 \001(\t\022\017\n\007luggage\030\002 \001(\0052\261\003\n\r" +
      "FlightService\022_\n\nflightList\022%.com.alexey" +
      "re.grpc.flight.ListRequest\032&.com.alexeyr" +
      "e.grpc.flight.ListResponse\"\0000\001\022h\n\rflight" +
      "Booking\022(.com.alexeyre.grpc.flight.Booki" +
      "ngRequest\032).com.alexeyre.grpc.flight.Boo" +
      "kingResponse\"\000(\001\022c\n\014flightPeople\022\'.com.a" +
      "lexeyre.grpc.flight.PeopleRequest\032(.com." +
      "alexeyre.grpc.flight.PeopleResponse\"\000\022p\n" +
      "\017flightPassenger\022*.com.alexeyre.grpc.fli" +
      "ght.PassengerRequest\032+.com.alexeyre.grpc" +
      ".flight.PassengerResponse\"\000(\0010\001B/\n\030com.a" +
      "lexeyre.grpc.flightB\021FlightServiceImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor,
        new java.lang.String[] { "Location1", "Location2", "Location3", "Location4", });
    internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alexeyre_grpc_flight_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alexeyre_grpc_flight_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_alexeyre_grpc_flight_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor,
        new java.lang.String[] { "ResponseCode", "ResponseMessage", "Depart", "DepartDate", "Arrival", "ArrivalDate", });
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor,
        new java.lang.String[] { "Passengers", });
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor,
        new java.lang.String[] { "Passengers", });
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor,
        new java.lang.String[] { "Seat", "Luggage", });
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor,
        new java.lang.String[] { "Seat", "Luggage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
