// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public final class FlightServiceImpl {
  private FlightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_ListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_BookingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_BookingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PeopleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PeopleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PassengerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alexeyre_grpc_flight_PassengerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014flight.proto\022\030com.alexeyre.grpc.flight" +
      "\"Y\n\013ListRequest\022\021\n\tlocation1\030\001 \001(\t\022\021\n\tlo" +
      "cation2\030\002 \001(\t\022\021\n\tlocation3\030\003 \001(\t\022\021\n\tloca" +
      "tion4\030\004 \001(\t\"\036\n\014ListResponse\022\016\n\006result\030\001 " +
      "\001(\t\"0\n\016BookingRequest\022\020\n\010location\030\001 \001(\t\022" +
      "\014\n\004date\030\002 \001(\t\"`\n\017BookingResponse\022\027\n\017resp" +
      "onseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\022" +
      "\020\n\010location\030\003 \001(\t\022\014\n\004date\030\004 \001(\t\"#\n\rPeopl" +
      "eRequest\022\022\n\npassengers\030\001 \001(\005\"$\n\016PeopleRe" +
      "sponse\022\022\n\npassengers\030\001 \001(\005\"1\n\020PassengerR" +
      "equest\022\014\n\004seat\030\001 \001(\t\022\017\n\007luggage\030\002 \001(\005\"2\n" +
      "\021PassengerResponse\022\014\n\004seat\030\001 \001(\t\022\017\n\007lugg" +
      "age\030\002 \001(\0052\261\003\n\rFlightService\022_\n\nflightLis" +
      "t\022%.com.alexeyre.grpc.flight.ListRequest" +
      "\032&.com.alexeyre.grpc.flight.ListResponse" +
      "\"\0000\001\022h\n\rflightBooking\022(.com.alexeyre.grp" +
      "c.flight.BookingRequest\032).com.alexeyre.g" +
      "rpc.flight.BookingResponse\"\000(\001\022c\n\014flight" +
      "People\022\'.com.alexeyre.grpc.flight.People" +
      "Request\032(.com.alexeyre.grpc.flight.Peopl" +
      "eResponse\"\000\022p\n\017flightPassenger\022*.com.ale" +
      "xeyre.grpc.flight.PassengerRequest\032+.com" +
      ".alexeyre.grpc.flight.PassengerResponse\"" +
      "\000(\0010\001B/\n\030com.alexeyre.grpc.flightB\021Fligh" +
      "tServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alexeyre_grpc_flight_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_ListRequest_descriptor,
        new java.lang.String[] { "Location1", "Location2", "Location3", "Location4", });
    internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alexeyre_grpc_flight_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_ListResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alexeyre_grpc_flight_BookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_BookingRequest_descriptor,
        new java.lang.String[] { "Location", "Date", });
    internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_alexeyre_grpc_flight_BookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_BookingResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", "Location", "Date", });
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_alexeyre_grpc_flight_PeopleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PeopleRequest_descriptor,
        new java.lang.String[] { "Passengers", });
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_alexeyre_grpc_flight_PeopleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PeopleResponse_descriptor,
        new java.lang.String[] { "Passengers", });
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_alexeyre_grpc_flight_PassengerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PassengerRequest_descriptor,
        new java.lang.String[] { "Seat", "Luggage", });
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_alexeyre_grpc_flight_PassengerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alexeyre_grpc_flight_PassengerResponse_descriptor,
        new java.lang.String[] { "Seat", "Luggage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
