// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location1 = 1;</code>
   */
  java.lang.String getLocation1();
  /**
   * <code>string location1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocation1Bytes();

  /**
   * <code>string location2 = 2;</code>
   */
  java.lang.String getLocation2();
  /**
   * <code>string location2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocation2Bytes();

  /**
   * <code>string location3 = 3;</code>
   */
  java.lang.String getLocation3();
  /**
   * <code>string location3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocation3Bytes();

  /**
   * <code>string location4 = 4;</code>
   */
  java.lang.String getLocation4();
  /**
   * <code>string location4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getLocation4Bytes();
}
