// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseResult = 1;</code>
   */
  java.lang.String getResponseResult();
  /**
   * <code>string responseResult = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseResultBytes();
}
