// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

public interface NumberRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.flight.NumberRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestValue = 1;</code>
   */
  java.lang.String getRequestValue();
  /**
   * <code>string requestValue = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestValueBytes();
}
