// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flight.proto

package com.alexeyre.grpc.flight;

/**
 * Protobuf type {@code com.alexeyre.grpc.flight.SearchResponse}
 */
public  final class SearchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.flight.SearchResponse)
    SearchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SearchResponse.newBuilder() to construct.
  private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchResponse() {
    depart_ = "";
    departDate_ = "";
    arrival_ = "";
    arrivalDate_ = "";
    passengers_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SearchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            depart_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            departDate_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            arrival_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            arrivalDate_ = s;
            break;
          }
          case 56: {

            passengers_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_SearchResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_SearchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.flight.SearchResponse.class, com.alexeyre.grpc.flight.SearchResponse.Builder.class);
  }

  public static final int DEPART_FIELD_NUMBER = 3;
  private volatile java.lang.Object depart_;
  /**
   * <code>string depart = 3;</code>
   */
  public java.lang.String getDepart() {
    java.lang.Object ref = depart_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      depart_ = s;
      return s;
    }
  }
  /**
   * <code>string depart = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDepartBytes() {
    java.lang.Object ref = depart_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      depart_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTDATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object departDate_;
  /**
   * <code>string departDate = 4;</code>
   */
  public java.lang.String getDepartDate() {
    java.lang.Object ref = departDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departDate_ = s;
      return s;
    }
  }
  /**
   * <code>string departDate = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDepartDateBytes() {
    java.lang.Object ref = departDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVAL_FIELD_NUMBER = 5;
  private volatile java.lang.Object arrival_;
  /**
   * <code>string arrival = 5;</code>
   */
  public java.lang.String getArrival() {
    java.lang.Object ref = arrival_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrival_ = s;
      return s;
    }
  }
  /**
   * <code>string arrival = 5;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalBytes() {
    java.lang.Object ref = arrival_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrival_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVALDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object arrivalDate_;
  /**
   * <code>string arrivalDate = 6;</code>
   */
  public java.lang.String getArrivalDate() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrivalDate_ = s;
      return s;
    }
  }
  /**
   * <code>string arrivalDate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalDateBytes() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSENGERS_FIELD_NUMBER = 7;
  private int passengers_;
  /**
   * <code>int32 passengers = 7;</code>
   */
  public int getPassengers() {
    return passengers_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDepartBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, depart_);
    }
    if (!getDepartDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, departDate_);
    }
    if (!getArrivalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, arrival_);
    }
    if (!getArrivalDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, arrivalDate_);
    }
    if (passengers_ != 0) {
      output.writeInt32(7, passengers_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDepartBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, depart_);
    }
    if (!getDepartDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, departDate_);
    }
    if (!getArrivalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, arrival_);
    }
    if (!getArrivalDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, arrivalDate_);
    }
    if (passengers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, passengers_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.flight.SearchResponse)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.flight.SearchResponse other = (com.alexeyre.grpc.flight.SearchResponse) obj;

    boolean result = true;
    result = result && getDepart()
        .equals(other.getDepart());
    result = result && getDepartDate()
        .equals(other.getDepartDate());
    result = result && getArrival()
        .equals(other.getArrival());
    result = result && getArrivalDate()
        .equals(other.getArrivalDate());
    result = result && (getPassengers()
        == other.getPassengers());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEPART_FIELD_NUMBER;
    hash = (53 * hash) + getDepart().hashCode();
    hash = (37 * hash) + DEPARTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDepartDate().hashCode();
    hash = (37 * hash) + ARRIVAL_FIELD_NUMBER;
    hash = (53 * hash) + getArrival().hashCode();
    hash = (37 * hash) + ARRIVALDATE_FIELD_NUMBER;
    hash = (53 * hash) + getArrivalDate().hashCode();
    hash = (37 * hash) + PASSENGERS_FIELD_NUMBER;
    hash = (53 * hash) + getPassengers();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.flight.SearchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.flight.SearchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.flight.SearchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.flight.SearchResponse)
      com.alexeyre.grpc.flight.SearchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_SearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.flight.SearchResponse.class, com.alexeyre.grpc.flight.SearchResponse.Builder.class);
    }

    // Construct using com.alexeyre.grpc.flight.SearchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      depart_ = "";

      departDate_ = "";

      arrival_ = "";

      arrivalDate_ = "";

      passengers_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.flight.FlightServiceImpl.internal_static_com_alexeyre_grpc_flight_SearchResponse_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.SearchResponse getDefaultInstanceForType() {
      return com.alexeyre.grpc.flight.SearchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.SearchResponse build() {
      com.alexeyre.grpc.flight.SearchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.flight.SearchResponse buildPartial() {
      com.alexeyre.grpc.flight.SearchResponse result = new com.alexeyre.grpc.flight.SearchResponse(this);
      result.depart_ = depart_;
      result.departDate_ = departDate_;
      result.arrival_ = arrival_;
      result.arrivalDate_ = arrivalDate_;
      result.passengers_ = passengers_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.flight.SearchResponse) {
        return mergeFrom((com.alexeyre.grpc.flight.SearchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.flight.SearchResponse other) {
      if (other == com.alexeyre.grpc.flight.SearchResponse.getDefaultInstance()) return this;
      if (!other.getDepart().isEmpty()) {
        depart_ = other.depart_;
        onChanged();
      }
      if (!other.getDepartDate().isEmpty()) {
        departDate_ = other.departDate_;
        onChanged();
      }
      if (!other.getArrival().isEmpty()) {
        arrival_ = other.arrival_;
        onChanged();
      }
      if (!other.getArrivalDate().isEmpty()) {
        arrivalDate_ = other.arrivalDate_;
        onChanged();
      }
      if (other.getPassengers() != 0) {
        setPassengers(other.getPassengers());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.flight.SearchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.flight.SearchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object depart_ = "";
    /**
     * <code>string depart = 3;</code>
     */
    public java.lang.String getDepart() {
      java.lang.Object ref = depart_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        depart_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string depart = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDepartBytes() {
      java.lang.Object ref = depart_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        depart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string depart = 3;</code>
     */
    public Builder setDepart(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      depart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string depart = 3;</code>
     */
    public Builder clearDepart() {
      
      depart_ = getDefaultInstance().getDepart();
      onChanged();
      return this;
    }
    /**
     * <code>string depart = 3;</code>
     */
    public Builder setDepartBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      depart_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object departDate_ = "";
    /**
     * <code>string departDate = 4;</code>
     */
    public java.lang.String getDepartDate() {
      java.lang.Object ref = departDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDepartDateBytes() {
      java.lang.Object ref = departDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departDate = 4;</code>
     */
    public Builder setDepartDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departDate = 4;</code>
     */
    public Builder clearDepartDate() {
      
      departDate_ = getDefaultInstance().getDepartDate();
      onChanged();
      return this;
    }
    /**
     * <code>string departDate = 4;</code>
     */
    public Builder setDepartDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrival_ = "";
    /**
     * <code>string arrival = 5;</code>
     */
    public java.lang.String getArrival() {
      java.lang.Object ref = arrival_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrival_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrival = 5;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalBytes() {
      java.lang.Object ref = arrival_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrival_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrival = 5;</code>
     */
    public Builder setArrival(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrival_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrival = 5;</code>
     */
    public Builder clearArrival() {
      
      arrival_ = getDefaultInstance().getArrival();
      onChanged();
      return this;
    }
    /**
     * <code>string arrival = 5;</code>
     */
    public Builder setArrivalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrival_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrivalDate_ = "";
    /**
     * <code>string arrivalDate = 6;</code>
     */
    public java.lang.String getArrivalDate() {
      java.lang.Object ref = arrivalDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrivalDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalDateBytes() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrivalDate = 6;</code>
     */
    public Builder setArrivalDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrivalDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalDate = 6;</code>
     */
    public Builder clearArrivalDate() {
      
      arrivalDate_ = getDefaultInstance().getArrivalDate();
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalDate = 6;</code>
     */
    public Builder setArrivalDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrivalDate_ = value;
      onChanged();
      return this;
    }

    private int passengers_ ;
    /**
     * <code>int32 passengers = 7;</code>
     */
    public int getPassengers() {
      return passengers_;
    }
    /**
     * <code>int32 passengers = 7;</code>
     */
    public Builder setPassengers(int value) {
      
      passengers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 passengers = 7;</code>
     */
    public Builder clearPassengers() {
      
      passengers_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.flight.SearchResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.flight.SearchResponse)
  private static final com.alexeyre.grpc.flight.SearchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.flight.SearchResponse();
  }

  public static com.alexeyre.grpc.flight.SearchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
    @java.lang.Override
    public SearchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SearchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.flight.SearchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

