// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.alexeyre.grpc.hotel;

public interface HotelListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.hotel.HotelListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hotel1 = 1;</code>
   */
  java.lang.String getHotel1();
  /**
   * <code>string hotel1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getHotel1Bytes();

  /**
   * <code>string hotel2 = 2;</code>
   */
  java.lang.String getHotel2();
  /**
   * <code>string hotel2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getHotel2Bytes();

  /**
   * <code>string hotel3 = 3;</code>
   */
  java.lang.String getHotel3();
  /**
   * <code>string hotel3 = 3;</code>
   */
  com.google.protobuf.ByteString
      getHotel3Bytes();

  /**
   * <code>string hotel4 = 4;</code>
   */
  java.lang.String getHotel4();
  /**
   * <code>string hotel4 = 4;</code>
   */
  com.google.protobuf.ByteString
      getHotel4Bytes();
}
