// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.alexeyre.grpc.hotel;

/**
 * Protobuf type {@code com.alexeyre.grpc.hotel.HotelBookingResponse}
 */
public  final class HotelBookingResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.hotel.HotelBookingResponse)
    HotelBookingResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HotelBookingResponse.newBuilder() to construct.
  private HotelBookingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HotelBookingResponse() {
    hotel_ = "";
    roomType_ = "";
    arrivalDate_ = "";
    leavingDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HotelBookingResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hotel_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            roomType_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            arrivalDate_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            leavingDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelBookingResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelBookingResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.hotel.HotelBookingResponse.class, com.alexeyre.grpc.hotel.HotelBookingResponse.Builder.class);
  }

  public static final int HOTEL_FIELD_NUMBER = 1;
  private volatile java.lang.Object hotel_;
  /**
   * <code>string hotel = 1;</code>
   */
  public java.lang.String getHotel() {
    java.lang.Object ref = hotel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hotel_ = s;
      return s;
    }
  }
  /**
   * <code>string hotel = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHotelBytes() {
    java.lang.Object ref = hotel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hotel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object roomType_;
  /**
   * <code>string roomType = 2;</code>
   */
  public java.lang.String getRoomType() {
    java.lang.Object ref = roomType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomType_ = s;
      return s;
    }
  }
  /**
   * <code>string roomType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRoomTypeBytes() {
    java.lang.Object ref = roomType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARRIVALDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object arrivalDate_;
  /**
   * <code>string arrivalDate = 3;</code>
   */
  public java.lang.String getArrivalDate() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrivalDate_ = s;
      return s;
    }
  }
  /**
   * <code>string arrivalDate = 3;</code>
   */
  public com.google.protobuf.ByteString
      getArrivalDateBytes() {
    java.lang.Object ref = arrivalDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrivalDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEAVINGDATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object leavingDate_;
  /**
   * <code>string leavingDate = 4;</code>
   */
  public java.lang.String getLeavingDate() {
    java.lang.Object ref = leavingDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      leavingDate_ = s;
      return s;
    }
  }
  /**
   * <code>string leavingDate = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLeavingDateBytes() {
    java.lang.Object ref = leavingDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      leavingDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHotelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hotel_);
    }
    if (!getRoomTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomType_);
    }
    if (!getArrivalDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, arrivalDate_);
    }
    if (!getLeavingDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, leavingDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHotelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hotel_);
    }
    if (!getRoomTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomType_);
    }
    if (!getArrivalDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, arrivalDate_);
    }
    if (!getLeavingDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, leavingDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.hotel.HotelBookingResponse)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.hotel.HotelBookingResponse other = (com.alexeyre.grpc.hotel.HotelBookingResponse) obj;

    boolean result = true;
    result = result && getHotel()
        .equals(other.getHotel());
    result = result && getRoomType()
        .equals(other.getRoomType());
    result = result && getArrivalDate()
        .equals(other.getArrivalDate());
    result = result && getLeavingDate()
        .equals(other.getLeavingDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOTEL_FIELD_NUMBER;
    hash = (53 * hash) + getHotel().hashCode();
    hash = (37 * hash) + ROOMTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getRoomType().hashCode();
    hash = (37 * hash) + ARRIVALDATE_FIELD_NUMBER;
    hash = (53 * hash) + getArrivalDate().hashCode();
    hash = (37 * hash) + LEAVINGDATE_FIELD_NUMBER;
    hash = (53 * hash) + getLeavingDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelBookingResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.hotel.HotelBookingResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.hotel.HotelBookingResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.hotel.HotelBookingResponse)
      com.alexeyre.grpc.hotel.HotelBookingResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelBookingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelBookingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.hotel.HotelBookingResponse.class, com.alexeyre.grpc.hotel.HotelBookingResponse.Builder.class);
    }

    // Construct using com.alexeyre.grpc.hotel.HotelBookingResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hotel_ = "";

      roomType_ = "";

      arrivalDate_ = "";

      leavingDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelBookingResponse_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelBookingResponse getDefaultInstanceForType() {
      return com.alexeyre.grpc.hotel.HotelBookingResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelBookingResponse build() {
      com.alexeyre.grpc.hotel.HotelBookingResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelBookingResponse buildPartial() {
      com.alexeyre.grpc.hotel.HotelBookingResponse result = new com.alexeyre.grpc.hotel.HotelBookingResponse(this);
      result.hotel_ = hotel_;
      result.roomType_ = roomType_;
      result.arrivalDate_ = arrivalDate_;
      result.leavingDate_ = leavingDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.hotel.HotelBookingResponse) {
        return mergeFrom((com.alexeyre.grpc.hotel.HotelBookingResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.hotel.HotelBookingResponse other) {
      if (other == com.alexeyre.grpc.hotel.HotelBookingResponse.getDefaultInstance()) return this;
      if (!other.getHotel().isEmpty()) {
        hotel_ = other.hotel_;
        onChanged();
      }
      if (!other.getRoomType().isEmpty()) {
        roomType_ = other.roomType_;
        onChanged();
      }
      if (!other.getArrivalDate().isEmpty()) {
        arrivalDate_ = other.arrivalDate_;
        onChanged();
      }
      if (!other.getLeavingDate().isEmpty()) {
        leavingDate_ = other.leavingDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.hotel.HotelBookingResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.hotel.HotelBookingResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hotel_ = "";
    /**
     * <code>string hotel = 1;</code>
     */
    public java.lang.String getHotel() {
      java.lang.Object ref = hotel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hotel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hotel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHotelBytes() {
      java.lang.Object ref = hotel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hotel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hotel = 1;</code>
     */
    public Builder setHotel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hotel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hotel = 1;</code>
     */
    public Builder clearHotel() {
      
      hotel_ = getDefaultInstance().getHotel();
      onChanged();
      return this;
    }
    /**
     * <code>string hotel = 1;</code>
     */
    public Builder setHotelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hotel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object roomType_ = "";
    /**
     * <code>string roomType = 2;</code>
     */
    public java.lang.String getRoomType() {
      java.lang.Object ref = roomType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roomType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRoomTypeBytes() {
      java.lang.Object ref = roomType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roomType = 2;</code>
     */
    public Builder setRoomType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roomType = 2;</code>
     */
    public Builder clearRoomType() {
      
      roomType_ = getDefaultInstance().getRoomType();
      onChanged();
      return this;
    }
    /**
     * <code>string roomType = 2;</code>
     */
    public Builder setRoomTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object arrivalDate_ = "";
    /**
     * <code>string arrivalDate = 3;</code>
     */
    public java.lang.String getArrivalDate() {
      java.lang.Object ref = arrivalDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrivalDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrivalDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getArrivalDateBytes() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrivalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrivalDate = 3;</code>
     */
    public Builder setArrivalDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrivalDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalDate = 3;</code>
     */
    public Builder clearArrivalDate() {
      
      arrivalDate_ = getDefaultInstance().getArrivalDate();
      onChanged();
      return this;
    }
    /**
     * <code>string arrivalDate = 3;</code>
     */
    public Builder setArrivalDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrivalDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object leavingDate_ = "";
    /**
     * <code>string leavingDate = 4;</code>
     */
    public java.lang.String getLeavingDate() {
      java.lang.Object ref = leavingDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leavingDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string leavingDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLeavingDateBytes() {
      java.lang.Object ref = leavingDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leavingDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string leavingDate = 4;</code>
     */
    public Builder setLeavingDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      leavingDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string leavingDate = 4;</code>
     */
    public Builder clearLeavingDate() {
      
      leavingDate_ = getDefaultInstance().getLeavingDate();
      onChanged();
      return this;
    }
    /**
     * <code>string leavingDate = 4;</code>
     */
    public Builder setLeavingDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      leavingDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.hotel.HotelBookingResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.hotel.HotelBookingResponse)
  private static final com.alexeyre.grpc.hotel.HotelBookingResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.hotel.HotelBookingResponse();
  }

  public static com.alexeyre.grpc.hotel.HotelBookingResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HotelBookingResponse>
      PARSER = new com.google.protobuf.AbstractParser<HotelBookingResponse>() {
    @java.lang.Override
    public HotelBookingResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HotelBookingResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HotelBookingResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HotelBookingResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.hotel.HotelBookingResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

