// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.alexeyre.grpc.hotel;

public interface HotelListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.hotel.HotelListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hotels = 1;</code>
   */
  java.lang.String getHotels();
  /**
   * <code>string hotels = 1;</code>
   */
  com.google.protobuf.ByteString
      getHotelsBytes();
}
