// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.alexeyre.grpc.hotel;

public interface HotelAmenitiesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alexeyre.grpc.hotel.HotelAmenitiesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool breakfast = 1;</code>
   */
  boolean getBreakfast();

  /**
   * <code>bool gym = 2;</code>
   */
  boolean getGym();
}
