// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.alexeyre.grpc.hotel;

/**
 * Protobuf type {@code com.alexeyre.grpc.hotel.HotelAmenitiesResponse}
 */
public  final class HotelAmenitiesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alexeyre.grpc.hotel.HotelAmenitiesResponse)
    HotelAmenitiesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HotelAmenitiesResponse.newBuilder() to construct.
  private HotelAmenitiesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HotelAmenitiesResponse() {
    breakfast_ = "";
    gym_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HotelAmenitiesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            breakfast_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            gym_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelAmenitiesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelAmenitiesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alexeyre.grpc.hotel.HotelAmenitiesResponse.class, com.alexeyre.grpc.hotel.HotelAmenitiesResponse.Builder.class);
  }

  public static final int BREAKFAST_FIELD_NUMBER = 1;
  private volatile java.lang.Object breakfast_;
  /**
   * <code>string breakfast = 1;</code>
   */
  public java.lang.String getBreakfast() {
    java.lang.Object ref = breakfast_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      breakfast_ = s;
      return s;
    }
  }
  /**
   * <code>string breakfast = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBreakfastBytes() {
    java.lang.Object ref = breakfast_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      breakfast_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GYM_FIELD_NUMBER = 2;
  private volatile java.lang.Object gym_;
  /**
   * <code>string gym = 2;</code>
   */
  public java.lang.String getGym() {
    java.lang.Object ref = gym_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gym_ = s;
      return s;
    }
  }
  /**
   * <code>string gym = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGymBytes() {
    java.lang.Object ref = gym_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gym_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBreakfastBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, breakfast_);
    }
    if (!getGymBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gym_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBreakfastBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, breakfast_);
    }
    if (!getGymBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gym_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alexeyre.grpc.hotel.HotelAmenitiesResponse)) {
      return super.equals(obj);
    }
    com.alexeyre.grpc.hotel.HotelAmenitiesResponse other = (com.alexeyre.grpc.hotel.HotelAmenitiesResponse) obj;

    boolean result = true;
    result = result && getBreakfast()
        .equals(other.getBreakfast());
    result = result && getGym()
        .equals(other.getGym());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BREAKFAST_FIELD_NUMBER;
    hash = (53 * hash) + getBreakfast().hashCode();
    hash = (37 * hash) + GYM_FIELD_NUMBER;
    hash = (53 * hash) + getGym().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alexeyre.grpc.hotel.HotelAmenitiesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alexeyre.grpc.hotel.HotelAmenitiesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alexeyre.grpc.hotel.HotelAmenitiesResponse)
      com.alexeyre.grpc.hotel.HotelAmenitiesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelAmenitiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelAmenitiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alexeyre.grpc.hotel.HotelAmenitiesResponse.class, com.alexeyre.grpc.hotel.HotelAmenitiesResponse.Builder.class);
    }

    // Construct using com.alexeyre.grpc.hotel.HotelAmenitiesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      breakfast_ = "";

      gym_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alexeyre.grpc.hotel.HotelServiceImpl.internal_static_com_alexeyre_grpc_hotel_HotelAmenitiesResponse_descriptor;
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelAmenitiesResponse getDefaultInstanceForType() {
      return com.alexeyre.grpc.hotel.HotelAmenitiesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelAmenitiesResponse build() {
      com.alexeyre.grpc.hotel.HotelAmenitiesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.alexeyre.grpc.hotel.HotelAmenitiesResponse buildPartial() {
      com.alexeyre.grpc.hotel.HotelAmenitiesResponse result = new com.alexeyre.grpc.hotel.HotelAmenitiesResponse(this);
      result.breakfast_ = breakfast_;
      result.gym_ = gym_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alexeyre.grpc.hotel.HotelAmenitiesResponse) {
        return mergeFrom((com.alexeyre.grpc.hotel.HotelAmenitiesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alexeyre.grpc.hotel.HotelAmenitiesResponse other) {
      if (other == com.alexeyre.grpc.hotel.HotelAmenitiesResponse.getDefaultInstance()) return this;
      if (!other.getBreakfast().isEmpty()) {
        breakfast_ = other.breakfast_;
        onChanged();
      }
      if (!other.getGym().isEmpty()) {
        gym_ = other.gym_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alexeyre.grpc.hotel.HotelAmenitiesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alexeyre.grpc.hotel.HotelAmenitiesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object breakfast_ = "";
    /**
     * <code>string breakfast = 1;</code>
     */
    public java.lang.String getBreakfast() {
      java.lang.Object ref = breakfast_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        breakfast_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string breakfast = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBreakfastBytes() {
      java.lang.Object ref = breakfast_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        breakfast_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string breakfast = 1;</code>
     */
    public Builder setBreakfast(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      breakfast_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string breakfast = 1;</code>
     */
    public Builder clearBreakfast() {
      
      breakfast_ = getDefaultInstance().getBreakfast();
      onChanged();
      return this;
    }
    /**
     * <code>string breakfast = 1;</code>
     */
    public Builder setBreakfastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      breakfast_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gym_ = "";
    /**
     * <code>string gym = 2;</code>
     */
    public java.lang.String getGym() {
      java.lang.Object ref = gym_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gym_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string gym = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGymBytes() {
      java.lang.Object ref = gym_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gym_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string gym = 2;</code>
     */
    public Builder setGym(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gym_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string gym = 2;</code>
     */
    public Builder clearGym() {
      
      gym_ = getDefaultInstance().getGym();
      onChanged();
      return this;
    }
    /**
     * <code>string gym = 2;</code>
     */
    public Builder setGymBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gym_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.alexeyre.grpc.hotel.HotelAmenitiesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.alexeyre.grpc.hotel.HotelAmenitiesResponse)
  private static final com.alexeyre.grpc.hotel.HotelAmenitiesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alexeyre.grpc.hotel.HotelAmenitiesResponse();
  }

  public static com.alexeyre.grpc.hotel.HotelAmenitiesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HotelAmenitiesResponse>
      PARSER = new com.google.protobuf.AbstractParser<HotelAmenitiesResponse>() {
    @java.lang.Override
    public HotelAmenitiesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HotelAmenitiesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HotelAmenitiesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HotelAmenitiesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.alexeyre.grpc.hotel.HotelAmenitiesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

